name = "paralogic"
version = "0.1.0"
defaultTargets = ["paralogic"]

# Look under src/ for your code and vendor/mathlib4 for Mathlib
lean_src_dirs = ["src", "vendor/mathlib4"]

[[lean_lib]]
name = "Paralogic"
path = "src/Paralogic"

[[lean_exe]]
name = "paralogic"
root = "src/Main"

[dependencies]
mathlib = { path = "vendor/mathlib4" }
