name="paralogic"
version="0.1.0"
lean_src_dirs=["src","vendor/mathlib4"]

[[lean_lib]]
name="Paralogic"
path="Paralogic"

[[lean_exe]]
name="paralogic"
root="Main"

[dependencies]
mathlib={path="vendor/mathlib4"}
