name: Lean Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-lean:
    runs-on: ubuntu-latest
    # Use the official Lean 4 container
    container:
      image: leanprover/lean4:latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Mathlib4
        run: lake update
      - name: Verify versions
        run: |
          lean --version
          lake --version
      - name: Build with Lake
        run: lake build
