name: Lean Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Lean & Lake via Elan
        uses: leanprover/elan-action@v2
        with:
          version: stable
      - name: Verify lean & lake versions
        run: |
          lean --version
          lake --version
      - name: Build with Lake
        run: lake build
