name: Lean Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-lean:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Install Elan & Lean 4 (using the correct install.sh on `main`)
      - name: Install Elan & Lean
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover-community/elan/main/install.sh \
            | sh -s -- --default-toolchain stable --force
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      # 3. Fetch Mathlib4 & generate lake-manifest.json
      - name: lake update
        run: lake update

      # 4. Verify lean & lake versions
      - name: Verify Versions
        run: |
          lean --version
          lake --version

      # 5. Build all proofs
      - name: Build with Lake
        run: lake build
