name: Lean Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Lean & Lake
        uses: leanprover/lean-action@v1
        with:
          auto-config: true   # detect lakefile.toml and run lake build

      - name: Verify versions
        run: |
          lean --version
          lake --version
