name: Lean Candidate Build

on:
  workflow_dispatch:

jobs:
  build-lean-candidate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install Elan
        uses: leanprover/elan-action@v1
        with:
          version: leanprover/lean4:v4.19.0
      - name: Show versions
        run: |
          lean --version
          lake --version
      - name: Candidate Lake build
        run: lake build
